<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IngredientsTableSeeder extends Seeder
{
    public function run(): void
    {
        $categories = DB::table('ingredient_categories')->pluck('id', 'name');

        $ingredients = [
            ['name' => 'Tomāts', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Kartupeļi', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Sīpols', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Burkāns', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Kāposts', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Gurķis', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Paprika', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Brokolis', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Spināti', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Cukini', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Skābenes', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Ziedkāposts', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Puravs', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Redīsi', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Lociņi', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Dilles', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Pētersīļi', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Selērija kāts', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Selērija sakne', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Baklažāns', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Ķirbis', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Lapu salāti', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Rukola', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Kabači', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Briseles kāposti', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Kukurūza', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Zirņi', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Zaļās pupiņas', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Ķiploks', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Čili pipars', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Mārrutki', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Biešu lapas', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Bietes', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Rabarberi', 'ingredient_category_id' => $categories['Dārzeņi']],
            ['name' => 'Nātru lapas', 'ingredient_category_id' => $categories['Dārzeņi']],

            ['name' => 'Ābols', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Banāns', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Apelsīns', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Citrons', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Mandarīns', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Ananāss', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Kivi', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Mango', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Bumbieris', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Vīnogas', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Avakado', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Persiks', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Nektarīns', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Plūme', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Melone', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Arbūzs', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Granātābols', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Papaija', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Greipfrūts', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Laims', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Hurma', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Guava', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Zvaigžņu auglis', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Dateles', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Vīģe', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Kokosrieksts', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Cukurniedres', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Upenes', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Sarkanās jāņogas', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Melenes', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Dzērvenes', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Kazenes', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Avenes', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Zemenes', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Meža zemenes', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Smiltsērkšķis', 'ingredient_category_id' => $categories['Augļi']],
            ['name' => 'Ērkšķogas', 'ingredient_category_id' => $categories['Augļi']],

            ['name' => 'Sāls', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Pipari', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Kumins', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Karijs', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Kanēlis', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Ingvers', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Laura lapas', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Rozmarīns', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Oregano', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Baziliks', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Koriandrs', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Paprikas pulveris', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Čili pulveris', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Kurkuma', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Krustnagliņas', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Sinepju sēklas', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Melnie pipari', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Baltie pipari', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Zaļie pipari', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Smiltsērkšķu pulveris', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Selerijas sāls', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Ķiploku pulveris', 'ingredient_category_id' => $categories['Garšvielas']],
            ['name' => 'Sīpolu pulveris', 'ingredient_category_id' => $categories['Garšvielas']],

            ['name' => 'Vistas fileja', 'ingredient_category_id' => $categories['Gaļas']],
            ['name' => 'Vistas gaļa', 'ingredient_category_id' => $categories['Gaļas']],
            ['name' => 'Cūkgaļa', 'ingredient_category_id' => $categories['Gaļas']],
            ['name' => 'Liellopa gaļa', 'ingredient_category_id' => $categories['Gaļas']],
            ['name' => 'Maltā gaļa', 'ingredient_category_id' => $categories['Gaļas']],
            ['name' => 'Bekons', 'ingredient_category_id' => $categories['Gaļas']],
            ['name' => 'Desa', 'ingredient_category_id' => $categories['Gaļas']],
            ['name' => 'Šķiņķis', 'ingredient_category_id' => $categories['Gaļas']],
            ['name' => 'Tītara gaļa', 'ingredient_category_id' => $categories['Gaļas']],
            ['name' => 'Cūkgaļas karbonāde', 'ingredient_category_id' => $categories['Gaļas']],
            ['name' => 'Cūkgaļas ribiņas', 'ingredient_category_id' => $categories['Gaļas']],
            ['name' => 'Liellopa steiks', 'ingredient_category_id' => $categories['Gaļas']],
            ['name' => 'Liellopa sautējuma gabali', 'ingredient_category_id' => $categories['Gaļas']],
            ['name' => 'Jēra gaļa', 'ingredient_category_id' => $categories['Gaļas']],
            ['name' => 'Speķis', 'ingredient_category_id' => $categories['Gaļas']],

            ['name' => 'Lasis', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Tuncis', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Garneles', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Zandarts', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Forele', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Heke', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Skumbrija', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Sardīnes', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Anšovi', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Mīdijas', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Kalmāri', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Astoņkāji', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Krabis', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Langusti', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Zivju fileja (jūras)', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Žāvēta zivs', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Kūpināts lasis', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Marinētas siļķes', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Zivju ikri', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Jūras aļģes (nori)', 'ingredient_category_id' => $categories['Jūras veltes']],
            ['name' => 'Zivis', 'ingredient_category_id' => $categories['Jūras veltes']],

            ['name' => 'Kviešu milti', 'ingredient_category_id' => $categories['Cepšanai']],
            ['name' => 'Pilngraudu milti', 'ingredient_category_id' => $categories['Cepšanai']],
            ['name' => 'Auzu milti', 'ingredient_category_id' => $categories['Cepšanai']],
            ['name' => 'Rudzu milti', 'ingredient_category_id' => $categories['Cepšanai']],
            ['name' => 'Kukurūzas milti', 'ingredient_category_id' => $categories['Cepšanai']],
            ['name' => 'Cepamais pulveris', 'ingredient_category_id' => $categories['Cepšanai']],
            ['name' => 'Soda (dzeramā)', 'ingredient_category_id' => $categories['Cepšanai']],
            ['name' => 'Kukurūzas ciete', 'ingredient_category_id' => $categories['Cepšanai']],
            ['name' => 'Kartupeļu ciete', 'ingredient_category_id' => $categories['Cepšanai']],
            ['name' => 'Raugs', 'ingredient_category_id' => $categories['Cepšanai']],
            ['name' => 'Želatīns', 'ingredient_category_id' => $categories['Cepšanai']],
            ['name' => 'Pīrāgu mīkla', 'ingredient_category_id' => $categories['Cepšanai']],

            ['name' => 'Rīsi', 'ingredient_category_id' => $categories['Graudu produkti']],
            ['name' => 'Makaroni', 'ingredient_category_id' => $categories['Graudu produkti']],
            ['name' => 'Kvinoja', 'ingredient_category_id' => $categories['Graudu produkti']],
            ['name' => 'Auzu pārslas', 'ingredient_category_id' => $categories['Graudu produkti']],
            ['name' => 'Mieži', 'ingredient_category_id' => $categories['Graudu produkti']],
            ['name' => 'Kvieši', 'ingredient_category_id' => $categories['Graudu produkti']],
            ['name' => 'Baltmaize', 'ingredient_category_id' => $categories['Graudu produkti']],
            ['name' => 'Rudzu maize', 'ingredient_category_id' => $categories['Graudu produkti']],
            ['name' => 'Griķi', 'ingredient_category_id' => $categories['Graudu produkti']],
            ['name' => 'Kukurūza', 'ingredient_category_id' => $categories['Graudu produkti']],
            ['name' => 'Milti', 'ingredient_category_id' => $categories['Graudu produkti']],
            ['name' => 'Lēcas', 'ingredient_category_id' => $categories['Graudu produkti']],

            ['name' => 'Piens', 'ingredient_category_id' => $categories['Piena produkti un olas']],
            ['name' => 'Saldais krējums', 'ingredient_category_id' => $categories['Piena produkti un olas']],
            ['name' => 'Skābais krējums', 'ingredient_category_id' => $categories['Piena produkti un olas']],
            ['name' => 'Jogurts', 'ingredient_category_id' => $categories['Piena produkti un olas']],
            ['name' => 'Grieķu jogurts', 'ingredient_category_id' => $categories['Piena produkti un olas']],
            ['name' => 'Biezpiens', 'ingredient_category_id' => $categories['Piena produkti un olas']],
            ['name' => 'Cietais siers', 'ingredient_category_id' => $categories['Piena produkti un olas']],
            ['name' => 'Kausētais siers', 'ingredient_category_id' => $categories['Piena produkti un olas']],
            ['name' => 'Feta siers', 'ingredient_category_id' => $categories['Piena produkti un olas']],
            ['name' => 'Siers', 'ingredient_category_id' => $categories['Piena produkti un olas']],
            ['name' => 'Mozarella', 'ingredient_category_id' => $categories['Piena produkti un olas']],
            ['name' => 'Parmezāns', 'ingredient_category_id' => $categories['Piena produkti un olas']],
            ['name' => 'Sviests', 'ingredient_category_id' => $categories['Piena produkti un olas']],
            ['name' => 'Olas', 'ingredient_category_id' => $categories['Piena produkti un olas']],
            ['name' => 'Olu baltums', 'ingredient_category_id' => $categories['Piena produkti un olas']],
            ['name' => 'Olu dzeltenums', 'ingredient_category_id' => $categories['Piena produkti un olas']],

            ['name' => 'Augu eļļa', 'ingredient_category_id' => $categories['Eļlas un tauki']],
            ['name' => 'Olīveļļa', 'ingredient_category_id' => $categories['Eļlas un tauki']],
            ['name' => 'Kokosriekstu eļļa', 'ingredient_category_id' => $categories['Eļlas un tauki']],
            ['name' => 'Sēklu eļļa', 'ingredient_category_id' => $categories['Eļlas un tauki']],
            ['name' => 'Rapsu eļļa', 'ingredient_category_id' => $categories['Eļlas un tauki']],
            ['name' => 'Zemesriekstu sviests', 'ingredient_category_id' => $categories['Eļlas un tauki']],
            ['name' => 'Linsēklu eļļa', 'ingredient_category_id' => $categories['Eļlas un tauki']],
            ['name' => 'Saulespuķu eļļa', 'ingredient_category_id' => $categories['Eļlas un tauki']],

            ['name' => 'Cukurs', 'ingredient_category_id' => $categories['Saldinātāji']],
            ['name' => 'Medus', 'ingredient_category_id' => $categories['Saldinātāji']],
            ['name' => 'Kokosriekstu cukurs', 'ingredient_category_id' => $categories['Saldinātāji']],
            ['name' => 'Stevija', 'ingredient_category_id' => $categories['Saldinātāji']],
            ['name' => 'Kļavu sīrups', 'ingredient_category_id' => $categories['Saldinātāji']],
            ['name' => 'Agaves sīrups', 'ingredient_category_id' => $categories['Saldinātāji']],
            ['name' => 'Bērzu sīrups', 'ingredient_category_id' => $categories['Saldinātāji']],
            ['name' => 'Rīsu sīrups', 'ingredient_category_id' => $categories['Saldinātāji']],

            ['name' => 'Ūdens', 'ingredient_category_id' => $categories['Šķidrumi']],
            ['name' => 'Ābolu sula', 'ingredient_category_id' => $categories['Šķidrumi']],
            ['name' => 'Apelsīnu sula', 'ingredient_category_id' => $categories['Šķidrumi']],
            ['name' => 'Tēja', 'ingredient_category_id' => $categories['Šķidrumi']],
            ['name' => 'Kafija', 'ingredient_category_id' => $categories['Šķidrumi']],
            ['name' => 'Kokteiļu sula', 'ingredient_category_id' => $categories['Šķidrumi']],
            ['name' => 'Mineralūdens', 'ingredient_category_id' => $categories['Šķidrumi']],
            ['name' => 'Kombuča', 'ingredient_category_id' => $categories['Šķidrumi']],
            ['name' => 'Kokosriekstu ūdens', 'ingredient_category_id' => $categories['Šķidrumi']],
            ['name' => 'Kokosriekstu piens', 'ingredient_category_id' => $categories['Šķidrumi']],
            ['name' => 'Vīns', 'ingredient_category_id' => $categories['Šķidrumi']],

            ['name' => 'Zemesrieksti', 'ingredient_category_id' => $categories['Rieksti un sēklas']],
            ['name' => 'Valrieksti', 'ingredient_category_id' => $categories['Rieksti un sēklas']],
            ['name' => 'Indijas rieksti', 'ingredient_category_id' => $categories['Rieksti un sēklas']],
            ['name' => 'Pistācijas', 'ingredient_category_id' => $categories['Rieksti un sēklas']],
            ['name' => 'Mandeles', 'ingredient_category_id' => $categories['Rieksti un sēklas']],
            ['name' => 'Lazdu rieksti', 'ingredient_category_id' => $categories['Rieksti un sēklas']],
            ['name' => 'Saulespuķu sēklas', 'ingredient_category_id' => $categories['Rieksti un sēklas']],
            ['name' => 'Ķirbju sēklas', 'ingredient_category_id' => $categories['Rieksti un sēklas']],
            ['name' => 'Čia sēklas', 'ingredient_category_id' => $categories['Rieksti un sēklas']],
            ['name' => 'Sezama sēklas', 'ingredient_category_id' => $categories['Rieksti un sēklas']],

            ['name' => 'Pētersīļi', 'ingredient_category_id' => $categories['Garšaugi']],
            ['name' => 'Dilles', 'ingredient_category_id' => $categories['Garšaugi']],
            ['name' => 'Baziliks', 'ingredient_category_id' => $categories['Garšaugi']],
            ['name' => 'Koriandrs', 'ingredient_category_id' => $categories['Garšaugi']],
            ['name' => 'Oregano', 'ingredient_category_id' => $categories['Garšaugi']],
            ['name' => 'Timiāns', 'ingredient_category_id' => $categories['Garšaugi']],
            ['name' => 'Rozmarīns', 'ingredient_category_id' => $categories['Garšaugi']],

            ['name' => 'Šampinjoni', 'ingredient_category_id' => $categories['Sēnes']],
            ['name' => 'Baravikas', 'ingredient_category_id' => $categories['Sēnes']],
            ['name' => 'Gailenes', 'ingredient_category_id' => $categories['Sēnes']],

            ['name' => 'Pupas', 'ingredient_category_id' => $categories['Pākšaugi']],
            ['name' => 'Zirņi', 'ingredient_category_id' => $categories['Pākšaugi']],
            ['name' => 'Melnās pupiņas', 'ingredient_category_id' => $categories['Pākšaugi']],
            ['name' => 'Sarkanās lēcas', 'ingredient_category_id' => $categories['Pākšaugi']],

            ['name' => 'Tumšā šokolāde', 'ingredient_category_id' => $categories['Saldumi']],
            ['name' => 'Baltā šokolāde', 'ingredient_category_id' => $categories['Saldumi']],
            ['name' => 'Želejas konfektes', 'ingredient_category_id' => $categories['Saldumi']],

            ['name' => 'Sarkanais vīns', 'ingredient_category_id' => $categories['Vīni, alus un degvīni']],
            ['name' => 'Baltais vīns', 'ingredient_category_id' => $categories['Vīni, alus un degvīni']],
            ['name' => 'Roze vīns', 'ingredient_category_id' => $categories['Vīni, alus un degvīni']],
            ['name' => 'Dzirkstošais vīns', 'ingredient_category_id' => $categories['Vīni, alus un degvīni']],
            ['name' => 'Portvīns', 'ingredient_category_id' => $categories['Vīni, alus un degvīni']],
            ['name' => 'Šerijs', 'ingredient_category_id' => $categories['Vīni, alus un degvīni']],
            ['name' => 'Alus', 'ingredient_category_id' => $categories['Vīni, alus un degvīni']],
            ['name' => 'Gaišais alus', 'ingredient_category_id' => $categories['Vīni, alus un degvīni']],
            ['name' => 'Tumšais alus', 'ingredient_category_id' => $categories['Vīni, alus un degvīni']],
            ['name' => 'Degvīns', 'ingredient_category_id' => $categories['Vīni, alus un degvīni']],
            ['name' => 'Konjaks', 'ingredient_category_id' => $categories['Vīni, alus un degvīni']],
            ['name' => 'Brendijs', 'ingredient_category_id' => $categories['Vīni, alus un degvīni']],
            ['name' => 'Rums', 'ingredient_category_id' => $categories['Vīni, alus un degvīni']],
            ['name' => 'Tekila', 'ingredient_category_id' => $categories['Vīni, alus un degvīni']],
            ['name' => 'Viskijs', 'ingredient_category_id' => $categories['Vīni, alus un degvīni']],
            ['name' => 'Liķieris', 'ingredient_category_id' => $categories['Vīni, alus un degvīni']],

            ['name' => 'Kečups', 'ingredient_category_id' => $categories['Mērces un piedevas']],
            ['name' => 'Sojas mērce', 'ingredient_category_id' => $categories['Mērces un piedevas']],
            ['name' => 'Majonēze', 'ingredient_category_id' => $categories['Mērces un piedevas']],
            ['name' => 'Sinepes', 'ingredient_category_id' => $categories['Mērces un piedevas']],
            ['name' => 'Pesto', 'ingredient_category_id' => $categories['Mērces un piedevas']],
            ['name' => 'BBQ mērce', 'ingredient_category_id' => $categories['Mērces un piedevas']],
            ['name' => 'Čili mērce', 'ingredient_category_id' => $categories['Mērces un piedevas']],
            ['name' => 'Saldskābā mērce', 'ingredient_category_id' => $categories['Mērces un piedevas']],
            ['name' => 'Tartara mērce', 'ingredient_category_id' => $categories['Mērces un piedevas']],
            ['name' => 'Teriyaki mērce', 'ingredient_category_id' => $categories['Mērces un piedevas']],
            ['name' => 'Zivju mērce', 'ingredient_category_id' => $categories['Mērces un piedevas']],
            ['name' => 'Worcestershire mērce', 'ingredient_category_id' => $categories['Mērces un piedevas']],
            ['name' => 'Ķiploku mērce', 'ingredient_category_id' => $categories['Mērces un piedevas']],

            ['name' => 'Konservēti tomāti', 'ingredient_category_id' => $categories['Konservēti produkti']],
            ['name' => 'Konservētas pupas', 'ingredient_category_id' => $categories['Konservēti produkti']],
            ['name' => 'Konservēta kukurūza', 'ingredient_category_id' => $categories['Konservēti produkti']],
            ['name' => 'Olīvas (bez kauliņiem)', 'ingredient_category_id' => $categories['Konservēti produkti']],

            ['name' => 'Sojas piens', 'ingredient_category_id' => $categories['Piena produktu alternatīvas']],
            ['name' => 'Bezlaktozes piens', 'ingredient_category_id' => $categories['Piena produktu alternatīvas']],
            ['name' => 'Mandeļu piens', 'ingredient_category_id' => $categories['Piena produktu alternatīvas']],
            ['name' => 'Auzu piens', 'ingredient_category_id' => $categories['Piena produktu alternatīvas']],
            ['name' => 'Kokosriekstu piens', 'ingredient_category_id' => $categories['Piena produktu alternatīvas']],
            ['name' => 'Rīsu piens', 'ingredient_category_id' => $categories['Piena produktu alternatīvas']],
            ['name' => 'Lazdu riekstu piens', 'ingredient_category_id' => $categories['Piena produktu alternatīvas']],
            ['name' => 'Kokosriekstu krēms', 'ingredient_category_id' => $categories['Piena produktu alternatīvas']],
            ['name' => 'Vegāniskais siers', 'ingredient_category_id' => $categories['Piena produktu alternatīvas']],
            ['name' => 'Vegāniskais krēmsiers', 'ingredient_category_id' => $categories['Piena produktu alternatīvas']],
            ['name' => 'Augu izcelsmes sviests', 'ingredient_category_id' => $categories['Piena produktu alternatīvas']],
        ];

        DB::table('ingredients')->insert($ingredients);
    }
}
