<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IngredientsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ingredients = [
            // Dārzeņi
            ['name' => 'Tomāts', 'category' => 'Dārzeņi'],
            ['name' => 'Kartupeļi', 'category' => 'Dārzeņi'],
            ['name' => 'Sīpols', 'category' => 'Dārzeņi'],
            ['name' => 'Burkāns', 'category' => 'Dārzeņi'],
            ['name' => 'Kāposts', 'category' => 'Dārzeņi'],
            ['name' => 'Gurķis', 'category' => 'Dārzeņi'],
            ['name' => 'Paprika', 'category' => 'Dārzeņi'],
            ['name' => 'Brokolis', 'category' => 'Dārzeņi'],
            ['name' => 'Spināti', 'category' => 'Dārzeņi'],
            ['name' => 'Cukini', 'category' => 'Dārzeņi'],
            ['name' => 'Skābenes', 'category' => 'Dārzeņi'],
            ['name' => 'Ziedkāposts', 'category' => 'Dārzeņi'],
            ['name' => 'Puravs', 'category' => 'Dārzeņi'],
            ['name' => 'Redīsi', 'category' => 'Dārzeņi'],
            ['name' => 'Lociņi', 'category' => 'Dārzeņi'],
            ['name' => 'Dilles', 'category' => 'Dārzeņi'],
            ['name' => 'Pētersīļi', 'category' => 'Dārzeņi'],
            ['name' => 'Selērija kāts', 'category' => 'Dārzeņi'],
            ['name' => 'Selērija sakne', 'category' => 'Dārzeņi'],
            ['name' => 'Baklažāns', 'category' => 'Dārzeņi'],
            ['name' => 'Ķirbis', 'category' => 'Dārzeņi'],
            ['name' => 'Lapu salāti', 'category' => 'Dārzeņi'],
            ['name' => 'Rukola', 'category' => 'Dārzeņi'],
            ['name' => 'Kabači', 'category' => 'Dārzeņi'],
            ['name' => 'Briseles kāposti', 'category' => 'Dārzeņi'],
            ['name' => 'Kukurūza', 'category' => 'Dārzeņi'],
            ['name' => 'Zirņi', 'category' => 'Dārzeņi'],
            ['name' => 'Zaļās pupiņas', 'category' => 'Dārzeņi'],
            ['name' => 'Ķiploks', 'category' => 'Dārzeņi'],
            ['name' => 'Čili pipars', 'category' => 'Dārzeņi'],
            ['name' => 'Mārrutki', 'category' => 'Dārzeņi'],
            ['name' => 'Biešu lapas', 'category' => 'Dārzeņi'],
            ['name' => 'Bietes', 'category' => 'Dārzeņi'],
            ['name' => 'Rabarberi', 'category' => 'Dārzeņi'],
            ['name' => 'Nātru lapas', 'category' => 'Dārzeņi'],  


            // Augļi
            ['name' => 'Ābols', 'category' => 'Augļi'],
            ['name' => 'Banāns', 'category' => 'Augļi'],
            ['name' => 'Apelsīns', 'category' => 'Augļi'],
            ['name' => 'Citrons', 'category' => 'Augļi'],
            ['name' => 'Mandarīns', 'category' => 'Augļi'],
            ['name' => 'Ananāss', 'category' => 'Augļi'],
            ['name' => 'Kivi', 'category' => 'Augļi'],
            ['name' => 'Mango', 'category' => 'Augļi'],
            ['name' => 'Bumbieris', 'category' => 'Augļi'],
            ['name' => 'Vīnogas', 'category' => 'Augļi'],
            ['name' => 'Avakado', 'category' => 'Augļi'],
            ['name' => 'Persiks', 'category' => 'Augļi'],
            ['name' => 'Nektarīns', 'category' => 'Augļi'],
            ['name' => 'Plūme', 'category' => 'Augļi'],
            ['name' => 'Melone', 'category' => 'Augļi'],
            ['name' => 'Arbūzs', 'category' => 'Augļi'],
            ['name' => 'Granātābols', 'category' => 'Augļi'],
            ['name' => 'Papaija', 'category' => 'Augļi'],
            ['name' => 'Greipfrūts', 'category' => 'Augļi'],
            ['name' => 'Laims', 'category' => 'Augļi'],
            ['name' => 'Hurma', 'category' => 'Augļi'],
            ['name' => 'Guava', 'category' => 'Augļi'],
            ['name' => 'Zvaigžņu auglis', 'category' => 'Augļi'],
            ['name' => 'Dateles', 'category' => 'Augļi'],
            ['name' => 'Vīģe', 'category' => 'Augļi'],
            ['name' => 'Kokosrieksts', 'category' => 'Augļi'],
            ['name' => 'Cukurniedres', 'category' => 'Augļi'],
            ['name' => 'Upenes', 'category' => 'Augļi'],
            ['name' => 'Sarkanās jāņogas', 'category' => 'Augļi'],
            ['name' => 'Melenes', 'category' => 'Augļi'],
            ['name' => 'Dzērvenes', 'category' => 'Augļi'],
            ['name' => 'Kazenes', 'category' => 'Augļi'],
            ['name' => 'Avenes', 'category' => 'Augļi'],
            ['name' => 'Zemenes', 'category' => 'Augļi'],
            ['name' => 'Meža zemenes', 'category' => 'Augļi'],
            ['name' => 'Smiltsērkšķis', 'category' => 'Augļi'],
            ['name' => 'Ērkšķogas', 'category' => 'Augļi'],


            // Garšvielas
            ['name' => 'Sāls', 'category' => 'Garšvielas'],
            ['name' => 'Pipari', 'category' => 'Garšvielas'],
            ['name' => 'Kumins', 'category' => 'Garšvielas'],
            ['name' => 'Karijs', 'category' => 'Garšvielas'],
            ['name' => 'Kanēlis', 'category' => 'Garšvielas'],
            ['name' => 'Ingvers', 'category' => 'Garšvielas'],
            ['name' => 'Laura lapas', 'category' => 'Garšvielas'],
            ['name' => 'Rozmarīns', 'category' => 'Garšvielas'],
            ['name' => 'Oregano', 'category' => 'Garšvielas'],
            ['name' => 'Baziliks', 'category' => 'Garšvielas'],
            ['name' => 'Koriandrs', 'category' => 'Garšvielas'],
            ['name' => 'Paprikas pulveris', 'category' => 'Garšvielas'],
            ['name' => 'Čili pulveris', 'category' => 'Garšvielas'],
            ['name' => 'Kurkuma', 'category' => 'Garšvielas'],
            ['name' => 'Krustnagliņas', 'category' => 'Garšvielas'],
            ['name' => 'Sinepju sēklas', 'category' => 'Garšvielas'],
            ['name' => 'Melnie pipari', 'category' => 'Garšvielas'],
            ['name' => 'Baltie pipari', 'category' => 'Garšvielas'],
            ['name' => 'Zaļie pipari', 'category' => 'Garšvielas'],
            ['name' => 'Smiltsērkšķu pulveris', 'category' => 'Garšvielas'],
            ['name' => 'Selerijas sāls', 'category' => 'Garšvielas'],
            ['name' => 'Ķiploku pulveris', 'category' => 'Garšvielas'],
            ['name' => 'Sīpolu pulveris', 'category' => 'Garšvielas'],

            // Gaļa
            ['name' => 'Vistas fileja', 'category' => 'Gaļas'],
            ['name' => 'Vistas gaļa', 'category' => 'Gaļas'],
            ['name' => 'Cūkgaļa', 'category' => 'Gaļas'],
            ['name' => 'Liellopa gaļa', 'category' => 'Gaļas'],
            ['name' => 'Maltā gaļa', 'category' => 'Gaļas'],
            ['name' => 'Bekons', 'category' => 'Gaļas'],
            ['name' => 'Desa', 'category' => 'Gaļas'],
            ['name' => 'Šķiņķis', 'category' => 'Gaļas'],
            ['name' => 'Tītara gaļa', 'category' => 'Gaļas'],
            ['name' => 'Cūkgaļas karbonāde', 'category' => 'Gaļas'],
            ['name' => 'Cūkgaļas ribiņas', 'category' => 'Gaļas'],
            ['name' => 'Liellopa steiks', 'category' => 'Gaļas'],
            ['name' => 'Liellopa sautējuma gabali', 'category' => 'Gaļas'],
            ['name' => 'Jēra gaļa', 'category' => 'Gaļas'],
            ['name' => 'Speķis', 'category' => 'Gaļas'],

            // Jūras veltes
            ['name' => 'Lasis', 'category' => 'Jūras veltes'],
            ['name' => 'Tuncis', 'category' => 'Jūras veltes'],
            ['name' => 'Garneles', 'category' => 'Jūras veltes'],
            ['name' => 'Zandarts', 'category' => 'Jūras veltes'],
            ['name' => 'Forele', 'category' => 'Jūras veltes'],
            ['name' => 'Heke', 'category' => 'Jūras veltes'],
            ['name' => 'Skumbrija', 'category' => 'Jūras veltes'],
            ['name' => 'Sardīnes', 'category' => 'Jūras veltes'],
            ['name' => 'Anšovi', 'category' => 'Jūras veltes'],
            ['name' => 'Mīdijas', 'category' => 'Jūras veltes'],
            ['name' => 'Kalmāri', 'category' => 'Jūras veltes'],
            ['name' => 'Astoņkāji', 'category' => 'Jūras veltes'],
            ['name' => 'Krabis', 'category' => 'Jūras veltes'],
            ['name' => 'Langusti', 'category' => 'Jūras veltes'],
            ['name' => 'Zivju fileja (jūras)', 'category' => 'Jūras veltes'],
            ['name' => 'Žāvēta zivs', 'category' => 'Jūras veltes'],
            ['name' => 'Kūpināts lasis', 'category' => 'Jūras veltes'],
            ['name' => 'Marinētas siļķes', 'category' => 'Jūras veltes'],
            ['name' => 'Zivju ikri', 'category' => 'Jūras veltes'],
            ['name' => 'Jūras aļģes (nori)', 'category' => 'Jūras veltes'],
            ['name' => 'Zivis', 'category' => 'Jūras veltes'],
            
            // baking
            ['name' => 'Kviešu milti', 'category' => 'Cepšanai'],
            ['name' => 'Pilngraudu milti', 'category' => 'Cepšanai'],
            ['name' => 'Auzu milti', 'category' => 'Cepšanai'],
            ['name' => 'Rudzu milti', 'category' => 'Cepšanai'],
            ['name' => 'Kukurūzas milti', 'category' => 'Cepšanai'],
            ['name' => 'Cepamais pulveris', 'category' => 'Cepšanai'],
            ['name' => 'Soda (dzeramā)', 'category' => 'Cepšanai'],
            ['name' => 'Kukurūzas ciete', 'category' => 'Cepšanai'],
            ['name' => 'Kartupeļu ciete', 'category' => 'Cepšanai'],
            ['name' => 'Raugs', 'category' => 'Cepšanai'],
            ['name' => 'Želatīns', 'category' => 'Cepšanai'],
            ['name' => 'Pīrāgu mīkla', 'category' => 'Cepšanai'],


            // Graudu produkti
            ['name' => 'Rīsi', 'category' => 'Graudu produkti'],
            ['name' => 'Makaroni', 'category' => 'Graudu produkti'],
            ['name' => 'Kvinoja', 'category' => 'Graudu produkti'],
            ['name' => 'Auzu pārslas', 'category' => 'Graudu produkti'],
            ['name' => 'Mieži', 'category' => 'Graudu produkti'],
            ['name' => 'Kvieši', 'category' => 'Graudu produkti'],
            ['name' => 'Baltmaize', 'category' => 'Graudu produkti'],
            ['name' => 'Rudzu maize', 'category' => 'Graudu produkti'],
            ['name' => 'Griķi', 'category' => 'Graudu produkti'],
            ['name' => 'Kukurūza', 'category' => 'Graudu produkti'],
            ['name' => 'Milti', 'category' => 'Graudu produkti'],
            ['name' => 'Lēcas', 'category' => 'Graudu produkti'],

            // Piena produkti un olas
            ['name' => 'Piens', 'category' => 'Piena produkti un olas'],
            ['name' => 'Saldais krējums', 'category' => 'Piena produkti un olas'],
            ['name' => 'Skābais krējums', 'category' => 'Piena produkti un olas'],
            ['name' => 'Jogurts', 'category' => 'Piena produkti un olas'],
            ['name' => 'Grieķu jogurts', 'category' => 'Piena produkti un olas'],
            ['name' => 'Biezpiens', 'category' => 'Piena produkti un olas'],
            ['name' => 'Cietais siers', 'category' => 'Piena produkti un olas'],
            ['name' => 'Kausētais siers', 'category' => 'Piena produkti un olas'],
            ['name' => 'Feta siers', 'category' => 'Piena produkti un olas'],
            ['name' => 'Siers', 'category' => 'Piena produkti un olas'],
            ['name' => 'Mozarella', 'category' => 'Piena produkti un olas'],
            ['name' => 'Parmezāns', 'category' => 'Piena produkti un olas'],
            ['name' => 'Sviests', 'category' => 'Piena produkti un olas'],
            ['name' => 'Olas', 'category' => 'Piena produkti un olas'],
            ['name' => 'Olu baltums', 'category' => 'Piena produkti un olas'],
            ['name' => 'Olu dzeltenums', 'category' => 'Piena produkti un olas'],

            // Eļlas un tauki
            ['name' => 'Augu eļļa', 'category' => 'Eļlas un tauki'],
            ['name' => 'Olīveļļa', 'category' => 'Eļlas un tauki'],
            ['name' => 'Kokosriekstu eļļa', 'category' => 'Eļlas un tauki'],
            ['name' => 'Sēklu eļļa', 'category' => 'Eļlas un tauki'],
            ['name' => 'Rapsu eļļa', 'category' => 'Eļlas un tauki'],
            ['name' => 'Zemesriekstu sviests', 'category' => 'Eļlas un tauki'],
            ['name' => 'Linsēklu eļļa', 'category' => 'Eļlas un tauki'],
            ['name' => 'Saulespuķu eļļa', 'category' => 'Eļlas un tauki'],

            // Saldinātāji
            ['name' => 'Cukurs', 'category' => 'Saldinātāji'],
            ['name' => 'Medus', 'category' => 'Saldinātāji'],
            ['name' => 'Kokosriekstu cukurs', 'category' => 'Saldinātāji'],
            ['name' => 'Stevija', 'category' => 'Saldinātāji'],
            ['name' => 'Kļavu sīrups', 'category' => 'Saldinātāji'],
            ['name' => 'Agaves sīrups', 'category' => 'Saldinātāji'],
            ['name' => 'Bērzu sīrups', 'category' => 'Saldinātāji'],
            ['name' => 'Rīsu sīrups', 'category' => 'Saldinātāji'],

            // Šķidrumi
            ['name' => 'Ūdens', 'category' => 'Šķidrumi'],
            ['name' => 'Ābolu sula', 'category' => 'Šķidrumi'],
            ['name' => 'Apelsīnu sula', 'category' => 'Šķidrumi'],
            ['name' => 'Tēja', 'category' => 'Šķidrumi'],
            ['name' => 'Kafija', 'category' => 'Šķidrumi'],
            ['name' => 'Kokteiļu sula', 'category' => 'Šķidrumi'],
            ['name' => 'Mineralūdens', 'category' => 'Šķidrumi'],
            ['name' => 'Kombuča', 'category' => 'Šķidrumi'],
            ['name' => 'Kokosriekstu ūdens', 'category' => 'Šķidrumi'],
            ['name' => 'Kokosriekstu piens', 'category' => 'Šķidrumi'],
            ['name' => 'Vīns', 'category' => 'Šķidrumi'],

            // Rieksti un sēklas
            ['name' => 'Zemesrieksti', 'category' => 'Rieksti un sēklas'],
            ['name' => 'Valrieksti', 'category' => 'Rieksti un sēklas'],
            ['name' => 'Indijas rieksti', 'category' => 'Rieksti un sēklas'],
            ['name' => 'Pistācijas', 'category' => 'Rieksti un sēklas'],
            ['name' => 'Mandeles', 'category' => 'Rieksti un sēklas'],
            ['name' => 'Lazdu rieksti', 'category' => 'Rieksti un sēklas'],
            ['name' => 'Saulespuķu sēklas', 'category' => 'Rieksti un sēklas'],
            ['name' => 'Ķirbju sēklas', 'category' => 'Rieksti un sēklas'],
            ['name' => 'Čia sēklas', 'category' => 'Rieksti un sēklas'],
            ['name' => 'Sezama sēklas', 'category' => 'Rieksti un sēklas'],

            // Garšaugi
            ['name' => 'Pētersīļi', 'category' => 'Garšaugi'],
            ['name' => 'Dilles', 'category' => 'Garšaugi'],
            ['name' => 'Baziliks', 'category' => 'Garšaugi'],
            ['name' => 'Koriandrs', 'category' => 'Garšaugi'],
            ['name' => 'Oregano', 'category' => 'Garšaugi'],
            ['name' => 'Timiāns', 'category' => 'Garšaugi'],
            ['name' => 'Rozmarīns', 'category' => 'Garšaugi'],

            // Sēnes
            ['name' => 'Šampinjoni', 'category' => 'Sēnes'],
            ['name' => 'Baravikas', 'category' => 'Sēnes'],
            ['name' => 'Gailenes', 'category' => 'Sēnes'],

            // Pākšaugi
            ['name' => 'Pupas', 'category' => 'Pākšaugi'],
            ['name' => 'Zirņi', 'category' => 'Pākšaugi'],
            ['name' => 'Melnās pupiņas', 'category' => 'Pākšaugi'],
            ['name' => 'Sarkanās lēcas', 'category' => 'Pākšaugi'],

            // Saldumi un našķi
            ['name' => 'Tumšā šokolāde', 'category' => 'Saldumi'],
            ['name' => 'Baltā šokolāde', 'category' => 'Saldumi'],
            ['name' => 'Želejas konfektes', 'category' => 'Saldumi'],

            // Alkoholiski dzērieni
            ['name' => 'Sarkanais vīns', 'category' => 'Vīni, alus un degvīni'],
            ['name' => 'Baltais vīns', 'category' => 'Vīni, alus un degvīni'],
            ['name' => 'Roze vīns', 'category' => 'Vīni, alus un degvīni'],
            ['name' => 'Dzirkstošais vīns', 'category' => 'Vīni, alus un degvīni'],
            ['name' => 'Portvīns', 'category' => 'Vīni, alus un degvīni'],
            ['name' => 'Šerijs', 'category' => 'Vīni, alus un degvīni'],
            ['name' => 'Alus', 'category' => 'Vīni, alus un degvīni'],
            ['name' => 'Gaišais alus', 'category' => 'Vīni, alus un degvīni'],
            ['name' => 'Tumšais alus', 'category' => 'Vīni, alus un degvīni'],
            ['name' => 'Degvīns', 'category' => 'Vīni, alus un degvīni'],
            ['name' => 'Konjaks', 'category' => 'Vīni, alus un degvīni'],
            ['name' => 'Brendijs', 'category' => 'Vīni, alus un degvīni'],
            ['name' => 'Rums', 'category' => 'Vīni, alus un degvīni'],
            ['name' => 'Tekila', 'category' => 'Vīni, alus un degvīni'],
            ['name' => 'Viskijs', 'category' => 'Vīni, alus un degvīni'],
            ['name' => 'Liķieris', 'category' => 'Vīni, alus un degvīni'],

            // Mērces un piedevas
            ['name' => 'Kečups', 'category' => 'Mērces un piedevas'],
            ['name' => 'Sojas mērce', 'category' => 'Mērces un piedevas'],
            ['name' => 'Majonēze', 'category' => 'Mērces un piedevas'],
            ['name' => 'Sinepes', 'category' => 'Mērces un piedevas'],
            ['name' => 'Pesto', 'category' => 'Mērces un piedevas'],
            ['name' => 'BBQ mērce', 'category' => 'Mērces un piedevas'],
            ['name' => 'Čili mērce', 'category' => 'Mērces un piedevas'],
            ['name' => 'Saldskābā mērce', 'category' => 'Mērces un piedevas'],
            ['name' => 'Tartara mērce', 'category' => 'Mērces un piedevas'],
            ['name' => 'Teriyaki mērce', 'category' => 'Mērces un piedevas'],
            ['name' => 'Zivju mērce', 'category' => 'Mērces un piedevas'],
            ['name' => 'Worcestershire mērce', 'category' => 'Mērces un piedevas'],
            ['name' => 'Ķiploku mērce', 'category' => 'Mērces un piedevas'],

            // Konservēti produkti
            ['name' => 'Konservēti tomāti',      'category' => 'Konservēti produkti'],
            ['name' => 'Konservētas pupas',       'category' => 'Konservēti produkti'],
            ['name' => 'Konservēta kukurūza',     'category' => 'Konservēti produkti'],
            ['name' => 'Olīvas (bez kauliņiem)', 'category' => 'Konservēti produkti'],

            // Piena produktu alternatīvas
            ['name' => 'Sojas piens', 'category' => 'Piena produktu alternatīvas'],
            ['name' => 'Bezlaktozes piens', 'category' => 'Piena produktu alternatīvas'],
            ['name' => 'Mandeļu piens', 'category' => 'Piena produktu alternatīvas'],
            ['name' => 'Auzu piens', 'category' => 'Piena produktu alternatīvas'],
            ['name' => 'Kokosriekstu piens', 'category' => 'Piena produktu alternatīvas'],
            ['name' => 'Rīsu piens', 'category' => 'Piena produktu alternatīvas'],
            ['name' => 'Lazdu riekstu piens', 'category' => 'Piena produktu alternatīvas'],
            ['name' => 'Kokosriekstu krēms', 'category' => 'Piena produktu alternatīvas'],
            ['name' => 'Vegāniskais siers', 'category' => 'Piena produktu alternatīvas'],
            ['name' => 'Vegāniskais krēmsiers', 'category' => 'Piena produktu alternatīvas'],
            ['name' => 'Augu izcelsmes sviests', 'category' => 'Piena produktu alternatīvas'],
        ];

        DB::table('ingredients')->insert($ingredients);
    }
}