<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class RecipesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('recipes')->delete();

        // Define image paths
        $imagePaths = [
            'omlete_ar_sieru.jpg' => '/omlete_ar_sieru.jpg',
            'bananu_pankukas.jpg' => '/bananu_pankukas.jpg',
            'abolu_pirags.jpg' => '/abolu_pirags.jpg',
            'auglu_salati.jpg' => '/auglu_salati.jpg',
            'auzu_parslas_ar_aboliem.jpg' => '/auzu_parslas_ar_aboliem.jpg',
            'avakado_tostermaize.jpg' => '/avakado_tostermaize.jpg',
            'burkanu_zupa.jpg' => '/burkanu_zupa.jpg',
            'grilleta_zivs.jpg' => '/grilleta_zivs.jpg',
            'gurku_tomatu_salati.jpg' => '/gurku_tomatu_salati.jpg',
            'kapostu_kartupelu_zupa.jpg' => '/kapostu_kartupelu_zupa.jpg',
            'kapostu_salati_burkani.jpg' => '/kapostu_salati_burkani.jpg',
            'kartupeli_rozmarins.jpg' => '/kartupeli_rozmarins.jpg',
            'lecu_spinatu_sautejums.jpg' => '/lecu_spinatu_sautejums.jpg',
            'mango_smutijs.jpg' => '/mango_smutijs.jpg',
            'pildita_paprika.jpg' => '/pildita_paprika.jpg',
            'spageti_kiploku_merce.jpg' => '/spageti_kiploku_merce.jpg',
            'tofu_karijs.webp' => '/tofu_karijs.webp',
            'tomatu_zupa.jpg' => '/tomatu_zupa.jpg',
            'vistas_risu_zupa.jpg' => '/vistas_risu_zupa.jpg',
            'vistas_sautejums.jpg' => '/vistas_sautejums.jpg',
        ];
        

        // Define new recipes
        $recipes = [
            // Brokastis un uzkodas
            [
                'nosaukums' => 'Omlete ar spinātiem un sieru',
                'apraksts' => 'Garšīga omlete ar svaigiem spinātiem un sieru.',
                'gatavosanas_laiks' => 15,
                'grutibas_pakape' => 'Viegls',
                'edienreize' => 'Brokastis',
                'uzturs' => 'Olbaltumvielu bagātas receptes',
                'dietas_tips' => 'Veģetāra',
                'galvenais_olbaltumvielu_avots' => 'Olas',
                'attels' => $imagePaths['omlete_ar_sieru.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],
            [
                'nosaukums' => 'Banānu pankūkas',
                'apraksts' => 'Pūkainas pankūkas ar banāniem.',
                'gatavosanas_laiks' => 20,
                'grutibas_pakape' => 'Viegls',
                'edienreize' => 'Brokastis',
                'uzturs' => 'Veģetāriešiem',
                'dietas_tips' => 'Veģetāra',
                'galvenais_olbaltumvielu_avots' => 'Olas',
                'attels' => $imagePaths['bananu_pankukas.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],
            [
                'nosaukums' => 'Auzu pārslas ar āboliem un kanēli',
                'apraksts' => 'Auzu pārslas ar svaigiem āboliem, kanēli un kļavu sīrupu.',
                'gatavosanas_laiks' => 10,
                'grutibas_pakape' => 'Viegls',
                'edienreize' => 'Brokastis',
                'uzturs' => 'Vegāniem',
                'dietas_tips' => 'Vegāna',
                'galvenais_olbaltumvielu_avots' => 'Bez Olbaltumvielām',
                'attels' => $imagePaths['auzu_parslas_ar_aboliem.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],
            [
                'nosaukums' => 'Avakado tostermaize ar olu',
                'apraksts' => 'Tostermaize ar avakado, olu un olīvu eļļu.',
                'gatavosanas_laiks' => 10,
                'grutibas_pakape' => 'Viegls',
                'edienreize' => 'Brokastis',
                'uzturs' => 'Olbaltumvielu bagātas receptes',
                'dietas_tips' => 'Veģetāra',
                'galvenais_olbaltumvielu_avots' => 'Olas',
                'attels' => $imagePaths['avakado_tostermaize.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],
            [
                'nosaukums' => 'Augļu salāti ar jogurtu',
                'apraksts' => 'Svaigu augļu salāti ar jogurtu un medu.',
                'gatavosanas_laiks' => 10,
                'grutibas_pakape' => 'Viegls',
                'edienreize' => 'Brokastis',
                'uzturs' => 'Veģetāriešiem',
                'dietas_tips' => 'Veģetāra',
                'galvenais_olbaltumvielu_avots' => 'Jogurts',
                'attels' => $imagePaths['auglu_salati.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],

            // Zupas un sautējumi
            [
                'nosaukums' => 'Tomātu zupa',
                'apraksts' => 'Klasiskā tomātu zupa ar krējumu.',
                'gatavosanas_laiks' => 30,
                'grutibas_pakape' => 'Vidējs',
                'edienreize' => 'Pusdienas',
                'uzturs' => 'Veģetāriešiem',
                'dietas_tips' => 'Veģetāra',
                'galvenais_olbaltumvielu_avots' => 'Bez Olbaltumvielām',
                'attels' => $imagePaths['tomatu_zupa.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],
            [
                'nosaukums' => 'Burkānu un ingvera zupa',
                'apraksts' => 'Siltā burkānu zupa ar ingveru.',
                'gatavosanas_laiks' => 35,
                'grutibas_pakape' => 'Vidējs',
                'edienreize' => 'Pusdienas',
                'uzturs' => 'Veģetāriešiem',
                'dietas_tips' => 'Veģetāra',
                'galvenais_olbaltumvielu_avots' => 'Bez Olbaltumvielām',
                'attels' => $imagePaths['burkanu_zupa.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],
            [
                'nosaukums' => 'Kāpostu un kartupeļu zupa',
                'apraksts' => 'Vienkārši pagatavojama zupa ar kāpostiem un kartupeļiem.',
                'gatavosanas_laiks' => 40,
                'grutibas_pakape' => 'Viegls',
                'edienreize' => 'Pusdienas',
                'uzturs' => 'Vegāniem',
                'dietas_tips' => 'Vegāna',
                'galvenais_olbaltumvielu_avots' => 'Bez Olbaltumvielām',
                'attels' => $imagePaths['kapostu_kartupelu_zupa.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],
            [
                'nosaukums' => 'Vistas un rīsu zupa',
                'apraksts' => 'Klasiska zupa ar vistas gaļu un rīsiem.',
                'gatavosanas_laiks' => 45,
                'grutibas_pakape' => 'Vidējs',
                'edienreize' => 'Pusdienas',
                'uzturs' => 'Olbaltumvielu bagātas receptes',
                'dietas_tips' => 'Gaļas',
                'galvenais_olbaltumvielu_avots' => 'Vistas gaļa',
                'attels' => $imagePaths['vistas_risu_zupa.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],
            [
                'nosaukums' => 'Lēcu un spinātu sautējums',
                'apraksts' => 'Sātīgs sautējums ar lēcām, spinātiem un tomātiem.',
                'gatavosanas_laiks' => 30,
                'grutibas_pakape' => 'Viegls',
                'edienreize' => 'Pusdienas',
                'uzturs' => 'Vegāniem',
                'dietas_tips' => 'Vegāna',
                'galvenais_olbaltumvielu_avots' => 'Bez Olbaltumvielām',
                'attels' => $imagePaths['lecu_spinatu_sautejums.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],

            // Galvenie ēdieni
            [
                'nosaukums' => 'Spageti ar ķiploku un sviesta mērci',
                'apraksts' => 'Vienkāršs ēdiens ar spageti, ķiplokiem un sviestu.',
                'gatavosanas_laiks' => 20,
                'grutibas_pakape' => 'Viegls',
                'edienreize' => 'Vakariņas',
                'uzturs' => 'Veģetāriešiem',
                'dietas_tips' => 'Veģetāra',
                'galvenais_olbaltumvielu_avots' => 'Makaroni',
                'attels' => $imagePaths['spageti_kiploku_merce.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],
            [
                'nosaukums' => 'Vistas sautējums ar dārzeņiem',
                'apraksts' => 'Sautējums ar vistas gaļu, brokoļiem, pipariem un sīpoliem.',
                'gatavosanas_laiks' => 25,
                'grutibas_pakape' => 'Vidējs',
                'edienreize' => 'Vakariņas',
                'uzturs' => 'Olbaltumvielu bagātas receptes',
                'dietas_tips' => 'Gaļas',
                'galvenais_olbaltumvielu_avots' => 'Vistas gaļa',
                'attels' => $imagePaths['vistas_sautejums.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],
            [
                'nosaukums' => 'Tofu un dārzeņu karijs',
                'apraksts' => 'Garšīgs karijs ar tofu, burkāniem, cukini un kokosriekstu pienu.',
                'gatavosanas_laiks' => 30,
                'grutibas_pakape' => 'Vidējs',
                'edienreize' => 'Vakariņas',
                'uzturs' => 'Olbaltumvielu bagātas receptes',
                'dietas_tips' => 'Vegāna',
                'galvenais_olbaltumvielu_avots' => 'Tofu',
                'attels' => $imagePaths['tofu_karijs.webp'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],
            [
                'nosaukums' => 'Pildīta piprika',
                'apraksts' => 'Paprika pildīta ar rīsiem, malto gaļu un tomātiem.',
                'gatavosanas_laiks' => 50,
                'grutibas_pakape' => 'Vidējs',
                'edienreize' => 'Vakariņas',
                'uzturs' => 'Olbaltumvielu bagātas receptes',
                'dietas_tips' => 'Gaļas',
                'galvenais_olbaltumvielu_avots' => 'Maltā gaļa',
                'attels' => $imagePaths['pildita_paprika.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],
            [
                'nosaukums' => 'Grilēta zivs',
                'apraksts' => 'Grilēta zivs ar aromātisku citronu un sviesta mērci.',
                'gatavosanas_laiks' => 25,
                'grutibas_pakape' => 'Vidējs',
                'edienreize' => 'Vakariņas',
                'uzturs' => 'Olbaltumvielu bagātas receptes',
                'dietas_tips' => 'Zivis',
                'galvenais_olbaltumvielu_avots' => 'Zivs',
                'attels' => $imagePaths['grilleta_zivs.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],

            // Piedevas
            [
                'nosaukums' => 'Cepti kartupeļi ar rozmarīnu',
                'apraksts' => 'Kartupeļi cepti ar rozmarīnu un olīvu eļļu.',
                'gatavosanas_laiks' => 30,
                'grutibas_pakape' => 'Viegls',
                'edienreize' => 'Piedeva',
                'uzturs' => 'Vegāniem',
                'dietas_tips' => 'Vegāna',
                'galvenais_olbaltumvielu_avots' => 'Bez Olbaltumvielām',
                'attels' => $imagePaths['kartupeli_rozmarins.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],
            [
                'nosaukums' => 'Kāpostu salāti',
                'apraksts' => 'Klasiskie kāpostu salāti ar burkāniem un jogurtu.',
                'gatavosanas_laiks' => 15,
                'grutibas_pakape' => 'Viegls',
                'edienreize' => 'Piedeva',
                'uzturs' => 'Veģetāriešiem',
                'dietas_tips' => 'Veģetāra',
                'galvenais_olbaltumvielu_avots' => 'Jogurts',
                'attels' => $imagePaths['kapostu_salati_burkani.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],
            [
                'nosaukums' => 'Gurķu un tomātu salāti',
                'apraksts' => 'Viegli salāti ar gurķiem, tomātiem un olīvu eļļu.',
                'gatavosanas_laiks' => 10,
                'grutibas_pakape' => 'Viegls',
                'edienreize' => 'Piedeva',
                'uzturs' => 'Vegāniem',
                'dietas_tips' => 'Vegāna',
                'galvenais_olbaltumvielu_avots' => 'Bez Olbaltumvielām',
                'attels' => $imagePaths['gurku_tomatu_salati.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],

            // Deserti
            [
                'nosaukums' => 'Ābolu pīrāgs ar kanēli',
                'apraksts' => 'Klasiskais ābolu pīrāgs ar kanēli un cukuru.',
                'gatavosanas_laiks' => 60,
                'grutibas_pakape' => 'Vidējs',
                'edienreize' => 'Deserts',
                'uzturs' => 'Veģetāriešiem',
                'dietas_tips' => 'Veģetāra',
                'galvenais_olbaltumvielu_avots' => 'Olas',
                'attels' => $imagePaths['abolu_pirags.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],
            [
                'nosaukums' => 'Mango smūtijs',
                'apraksts' => 'Atspirdzinošs smūtijs ar mango, jogurtu un medu.',
                'gatavosanas_laiks' => 10,
                'grutibas_pakape' => 'Viegls',
                'edienreize' => 'Deserts',
                'uzturs' => 'Veģetāriešiem',
                'dietas_tips' => 'Veģetāra',
                'galvenais_olbaltumvielu_avots' => 'Jogurts',
                'attels' => $imagePaths['mango_smutijs.jpg'],
                'datums_izveidots' => Carbon::now(),
                'datums_atjauninats' => Carbon::now(),
                'ir_publiska' => true,
            ],
        ];

        // Insert new recipes
        DB::table('recipes')->insert($recipes);
    }
}